export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_BY_WEIGHT = "ORDER_BY_WEIGHT";
export const GET_DOGS = "GET_DOGS";
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
export const GET_FILTER_TEMPERAMENTS = "GET_FILTER_TEMPERAMENTS";
export const GET_FILTER_RAZA = "GET_FILTER_RAZA";
export const FILTER_CREATED = "FILTER_CREATED";
export const GET_NAME_DOGS = "GET_NAME_DOGS";
export const POST_DOGS = "POST_DOGS";
export const GET_DETAILS = "GET_DETAILS";


