export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const GET_DOGS = "GET_DOGS";
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS"
export const GET_FILTER_TEMPERAMENTS = "GET_FILTER_TEMPERAMENTS"
export const GET_FILTER_RAZA = "GET_FILTER_RAZA"

